// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ErrorResponseErrorCode.
const (
	ASSISTANTINACTIVE ErrorResponseErrorCode = "ASSISTANT_INACTIVE"
	ASSISTANTNOTFOUND ErrorResponseErrorCode = "ASSISTANT_NOT_FOUND"
	CATEGORYNOTFOUND  ErrorResponseErrorCode = "CATEGORY_NOT_FOUND"
	FORBIDDEN         ErrorResponseErrorCode = "FORBIDDEN"
	INTERNALERROR     ErrorResponseErrorCode = "INTERNAL_ERROR"
	INVALIDREQUEST    ErrorResponseErrorCode = "INVALID_REQUEST"
	LLMPROVIDERERROR  ErrorResponseErrorCode = "LLM_PROVIDER_ERROR"
	NOTFOUND          ErrorResponseErrorCode = "NOT_FOUND"
	UNAUTHORIZED      ErrorResponseErrorCode = "UNAUTHORIZED"
)

// Defines values for Role.
const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

// Defines values for RunFeedbackRating.
const (
	Minus1 RunFeedbackRating = -1
	N1     RunFeedbackRating = 1
)

// Defines values for RunStatus.
const (
	Failed  RunStatus = "failed"
	Pending RunStatus = "pending"
	Success RunStatus = "success"
)

// Assistant defines model for Assistant.
type Assistant struct {
	CategoryId        openapi_types.UUID `json:"categoryId"`
	CategoryName      *string            `json:"categoryName"`
	CreatedAt         *time.Time         `json:"createdAt"`
	Description       string             `json:"description"`
	ExampleUserPrompt *string            `json:"exampleUserPrompt"`
	Id                openapi_types.UUID `json:"id"`
	IsActive          bool               `json:"isActive"`
	Model             string             `json:"model"`
	Name              string             `json:"name"`

	// SystemPrompt Может быть скрыт от обычного пользователя по решению кандидата
	SystemPrompt *string    `json:"systemPrompt"`
	UpdatedAt    *time.Time `json:"updatedAt"`
}

// AssistantCreateIn defines model for AssistantCreateIn.
type AssistantCreateIn struct {
	CategoryId        openapi_types.UUID `json:"categoryId"`
	Description       string             `json:"description"`
	ExampleUserPrompt *string            `json:"exampleUserPrompt"`
	IsActive          *bool              `json:"isActive,omitempty"`
	Model             string             `json:"model"`
	Name              string             `json:"name"`
	SystemPrompt      string             `json:"systemPrompt"`
}

// AssistantRun defines model for AssistantRun.
type AssistantRun struct {
	AssistantId    openapi_types.UUID  `json:"assistantId"`
	AssistantName  *string             `json:"assistantName"`
	CategoryId     *openapi_types.UUID `json:"categoryId"`
	CategoryName   *string             `json:"categoryName"`
	CreatedAt      *time.Time          `json:"createdAt"`
	Error          *string             `json:"error"`
	FeedbackRating *RunFeedbackRating  `json:"feedbackRating"`
	Id             openapi_types.UUID  `json:"id"`
	Model          string              `json:"model"`
	Output         *string             `json:"output"`

	// Status pending — запуск создан, но ответ ещё не получен; success — запуск завершился успешно; failed — запуск завершился ошибкой.
	Status     RunStatus          `json:"status"`
	UserId     openapi_types.UUID `json:"userId"`
	UserPrompt string             `json:"userPrompt"`
}

// AssistantRunCreateIn defines model for AssistantRunCreateIn.
type AssistantRunCreateIn struct {
	UserPrompt string `json:"userPrompt"`
}

// AssistantUpdateIn defines model for AssistantUpdateIn.
type AssistantUpdateIn struct {
	CategoryId        openapi_types.UUID `json:"categoryId"`
	Description       string             `json:"description"`
	ExampleUserPrompt *string            `json:"exampleUserPrompt"`
	IsActive          bool               `json:"isActive"`
	Model             string             `json:"model"`
	Name              string             `json:"name"`
	SystemPrompt      string             `json:"systemPrompt"`
}

// Category defines model for Category.
type Category struct {
	CreatedAt   *time.Time         `json:"createdAt"`
	Description *string            `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// CategoryCreateIn defines model for CategoryCreateIn.
type CategoryCreateIn struct {
	Description *string `json:"description"`
	Name        string  `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// Pagination defines model for Pagination.
type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
	Total    int `json:"total"`
}

// Role defines model for Role.
type Role string

// RunFeedbackRating -1 — дизлайк, 1 — лайк.
type RunFeedbackRating int32

// RunFeedbackUpsertIn defines model for RunFeedbackUpsertIn.
type RunFeedbackUpsertIn struct {
	// Rating -1 — дизлайк, 1 — лайк.
	Rating RunFeedbackRating `json:"rating"`
}

// RunStatus pending — запуск создан, но ответ ещё не получен; success — запуск завершился успешно; failed — запуск завершился ошибкой.
type RunStatus string

// Token defines model for Token.
type Token struct {
	// Token JWT для заголовка Authorization Bearer
	Token string `json:"token"`
	User  User   `json:"user"`
}

// User defines model for User.
type User struct {
	CreatedAt *time.Time          `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Role      Role                `json:"role"`
}

// AssistantIdPath defines model for AssistantIdPath.
type AssistantIdPath = openapi_types.UUID

// RunIdPath defines model for RunIdPath.
type RunIdPath = openapi_types.UUID

// GetAdminRunsParams defines parameters for GetAdminRuns.
type GetAdminRunsParams struct {
	AssistantId *openapi_types.UUID `form:"assistantId,omitempty" json:"assistantId,omitempty"`
	Status      *RunStatus          `form:"status,omitempty" json:"status,omitempty"`
	Page        *int                `form:"page,omitempty" json:"page,omitempty"`
	PageSize    *int                `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// GetAssistantsParams defines parameters for GetAssistants.
type GetAssistantsParams struct {
	// CategoryId Фильтр по категории
	CategoryId *openapi_types.UUID `form:"categoryId,omitempty" json:"categoryId,omitempty"`

	// Q Поиск по названию и описанию
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// IncludeInactive Фильтр "Показать неактивных ассистентов"; доступен администратору
	IncludeInactive *bool `form:"includeInactive,omitempty" json:"includeInactive,omitempty"`
	Page            *int  `form:"page,omitempty" json:"page,omitempty"`
	PageSize        *int  `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostDummyLoginJSONBody defines parameters for PostDummyLogin.
type PostDummyLoginJSONBody struct {
	Role Role `json:"role"`
}

// GetRunsMyParams defines parameters for GetRunsMy.
type GetRunsMyParams struct {
	Status   *RunStatus `form:"status,omitempty" json:"status,omitempty"`
	Page     *int       `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int       `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// PostAssistantsJSONRequestBody defines body for PostAssistants for application/json ContentType.
type PostAssistantsJSONRequestBody = AssistantCreateIn

// PutAssistantsAssistantIdJSONRequestBody defines body for PutAssistantsAssistantId for application/json ContentType.
type PutAssistantsAssistantIdJSONRequestBody = AssistantUpdateIn

// PostAssistantsAssistantIdRunJSONRequestBody defines body for PostAssistantsAssistantIdRun for application/json ContentType.
type PostAssistantsAssistantIdRunJSONRequestBody = AssistantRunCreateIn

// PostAssistantsAssistantIdRunStreamJSONRequestBody defines body for PostAssistantsAssistantIdRunStream for application/json ContentType.
type PostAssistantsAssistantIdRunStreamJSONRequestBody = AssistantRunCreateIn

// PostCategoriesJSONRequestBody defines body for PostCategories for application/json ContentType.
type PostCategoriesJSONRequestBody = CategoryCreateIn

// PostDummyLoginJSONRequestBody defines body for PostDummyLogin for application/json ContentType.
type PostDummyLoginJSONRequestBody PostDummyLoginJSONBody

// PutRunsRunIdFeedbackJSONRequestBody defines body for PutRunsRunIdFeedback for application/json ContentType.
type PutRunsRunIdFeedbackJSONRequestBody = RunFeedbackUpsertIn
