/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dummyLogin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Получить тестовый JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        role: components["schemas"]["Role"];
                    };
                };
            };
            responses: {
                /** @description JWT и пользователь */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Token"];
                    };
                };
                /** @description Некорректный запрос */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список категорий */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список категорий */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            categories: components["schemas"]["Category"][];
                        };
                    };
                };
                /** @description Нет авторизации */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Создать категорию */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryCreateIn"];
                };
            };
            responses: {
                /** @description Категория создана */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                /** @description Недостаточно прав */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список ассистентов */
        get: {
            parameters: {
                query?: {
                    /** @description Фильтр по категории */
                    categoryId?: string;
                    /** @description Поиск по названию и описанию */
                    q?: string;
                    /** @description Фильтр "Показать неактивных ассистентов"; доступен администратору */
                    includeInactive?: boolean;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список ассистентов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            assistants: components["schemas"]["Assistant"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
                /** @description Нет авторизации */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Создать ассистента */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantCreateIn"];
                };
            };
            responses: {
                /** @description Ассистент создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Assistant"];
                    };
                };
                /** @description Некорректный запрос */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Недостаточно прав */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistants/{assistantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить ассистента */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор ассистента */
                    assistantId: components["parameters"]["AssistantIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ассистент */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Assistant"];
                    };
                };
                /** @description Ассистент не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Обновить ассистента */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор ассистента */
                    assistantId: components["parameters"]["AssistantIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantUpdateIn"];
                };
            };
            responses: {
                /** @description Ассистент обновлён */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Assistant"];
                    };
                };
                /** @description Недостаточно прав */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Ассистент не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistants/{assistantId}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запустить ассистента
         * @description Backend использует системный промпт ассистента и пользовательский промпт из тела запроса.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор ассистента */
                    assistantId: components["parameters"]["AssistantIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantRunCreateIn"];
                };
            };
            responses: {
                /** @description Запуск создан или завершён */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssistantRun"];
                    };
                };
                /** @description Некорректный запрос */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Ассистент выключен */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Ошибка LLM-провайдера */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistants/{assistantId}/run/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запустить ассистента со streaming-ответом
         * @description Backend создаёт pending-запуск, отдаёт прогресс генерации через Server-Sent Events и после завершения сохраняет финальный output в историю. События: `run` — созданный pending-запуск (`AssistantRun`); `delta` — фрагмент ответа (`AssistantRunStreamDelta`); `done` — финальный успешный запуск (`AssistantRun`); `failed` — финальный failed-запуск и ошибка (`AssistantRunStreamFailure`).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Идентификатор ассистента */
                    assistantId: components["parameters"]["AssistantIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssistantRunCreateIn"];
                };
            };
            responses: {
                /** @description SSE-поток прогресса генерации */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description Некорректный запрос */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Требуется аутентификация */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Ассистент не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Ассистент выключен */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Внутренняя ошибка до старта SSE-потока */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Ошибка LLM-провайдера до старта SSE-потока */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История запусков текущего пользователя */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["RunStatus"];
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description История запусков */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            runs: components["schemas"]["AssistantRun"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все запуски ассистентов для администратора */
        get: {
            parameters: {
                query?: {
                    assistantId?: string;
                    status?: components["schemas"]["RunStatus"];
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список запусков */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            runs: components["schemas"]["AssistantRun"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
                /** @description Недостаточно прав */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "error": {
         *         "code": "INVALID_REQUEST",
         *         "message": "invalid request"
         *       }
         *     }
         */
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "INVALID_REQUEST" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CATEGORY_NOT_FOUND" | "ASSISTANT_NOT_FOUND" | "ASSISTANT_INACTIVE" | "LLM_PROVIDER_ERROR" | "INTERNAL_ERROR";
                message: string;
            };
        };
        Pagination: {
            page: number;
            pageSize: number;
            total: number;
        };
        /** @enum {string} */
        Role: "admin" | "user";
        Token: {
            /** @description JWT для заголовка Authorization Bearer */
            token: string;
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            createdAt?: string | null;
        };
        Category: {
            /** Format: uuid */
            id: string;
            /** @example Еда */
            name: string;
            description?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
        };
        CategoryCreateIn: {
            name: string;
            description?: string | null;
        };
        Assistant: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            categoryId: string;
            categoryName?: string | null;
            /** @example Повар */
            name: string;
            /** @example Составляет подробный рецепт по списку ингредиентов */
            description: string;
            /** @example mock-smart */
            model: string;
            /** @description Может быть скрыт от обычного пользователя по решению кандидата */
            systemPrompt?: string | null;
            /** @example курица, рис, томаты, сыр */
            exampleUserPrompt?: string | null;
            isActive: boolean;
            /** Format: date-time */
            createdAt?: string | null;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        AssistantCreateIn: {
            /** Format: uuid */
            categoryId: string;
            name: string;
            description: string;
            model: string;
            systemPrompt: string;
            exampleUserPrompt?: string | null;
            /** @default true */
            isActive: boolean;
        };
        AssistantUpdateIn: {
            /** Format: uuid */
            categoryId: string;
            name: string;
            description: string;
            model: string;
            systemPrompt: string;
            exampleUserPrompt?: string | null;
            isActive: boolean;
        };
        /**
         * @description pending — запуск создан, но ответ ещё не получен; success — запуск завершился успешно; failed — запуск завершился ошибкой.
         * @enum {string}
         */
        RunStatus: "pending" | "success" | "failed";
        AssistantRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assistantId: string;
            assistantName?: string | null;
            /** Format: uuid */
            categoryId?: string | null;
            categoryName?: string | null;
            /** Format: uuid */
            userId: string;
            model: string;
            userPrompt: string;
            output?: string | null;
            status: components["schemas"]["RunStatus"];
            error?: string | null;
            /** Format: date-time */
            createdAt?: string | null;
        };
        AssistantRunCreateIn: {
            userPrompt: string;
        };
        AssistantRunStreamDelta: {
            /** @description Очередной фрагмент ответа LLM. */
            delta: string;
        };
        AssistantRunStreamFailure: {
            run: components["schemas"]["AssistantRun"];
            error: components["schemas"]["ErrorResponse"]["error"];
        };
    };
    responses: never;
    parameters: {
        /** @description Идентификатор категории */
        CategoryIdPath: string;
        /** @description Идентификатор ассистента */
        AssistantIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
